version: '3.2'

services:

  app:
    image: dasos/peoplesplaylist
    ports:
     - 5000:5000
    environment:
     - SPOTIPY_CLIENT_ID=<client id>
     - SPOTIPY_CLIENT_SECRET=<client secret>
     - SPOTIPY_REDIRECT_URI=<redirect uri>
    volumes:
     # Make sure the file exists on your Docker host!
     - ./spotipy-cache:/tmp/spotipy-cache
